# ?????
#spring.datasource.url=jdbc:mysql://localhost:3306/ctms_demo?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.url=jdbc:mysql://172.16.101.193:3307/ctms_demo?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
#spring.datasource.password=www2580789
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect


# Spring Boot ?????????IPv4 ? IPv6?
server.address=0.0.0.0
server.port=8080

#spring.datasource.password=www2580789

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# MyBatis XML ??????
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



# JWT ??
sky.jwt.userSecretKey=myUserSecretKey123
sky.jwt.userTtl=86400000
sky.jwt.userTokenName=cao



file.upload-path=${FILE_UPLOAD_PATH:D:/yan/upload}
file.base-url=${FILE_BASE_URL:}
#file.upload-path=/opt/upload/
#file.base-url=http://172.16.101.193
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
